apiVersion: v1
kind: Pod
metadata:
  name: "tls-demo"
  labels:
    app: tls-demo
spec:
  containers:
    - name: nginx
      image: "nginx:1.9.14"
      lifecycle:
        preStop:
          exec:
            command: ["/usr/sbin/nginx","-s","quit"]
      volumeMounts:
        - name: "nginx-proxy-conf"
          mountPath: "/etc/nginx/conf.d"
        - name: "tls-demo"
          mountPath: "/etc/tls"
  volumes:
    - name: "tls-demo"
      secret:
        secretName: "tls-demo"
    - name: "nginx-proxy-conf"
      configMap:
        name: "configmap-demo"
        items:
          - key: "proxy.conf"
            path: "proxy.conf"
